# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='likes_books.User'),
        ),
    ]
