# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_login', '0003_auto_20181015_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.EmailField(max_length=255),
        ),
    ]
