# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_auto_20181018_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
